### ISSUE TITLE
Case sensitivity

### ISSUE THREAD

**Issue by spond** [stephenshank/jav#1]
Dear @stephenshank,

Attempting to load a valid FASTA file with lower case sequences displays no error messages but only black boxes.

Best,
Sergei

**Comment by stephenshank** [comment]
Dear @spond,

Thanks for reporting... this is addressed in https://github.com/stephenshank/jav/commit/78dd6cc716868ef04651343776c7c2e5d6c69f20 (see the CVF example).

Best,
Stephen
